### ISSUE TITLE
Punch time corrections not possible: Form not saved

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#22]
**Describe the bug**
When a user missed to clock in, it's not possible to create a new attendance.

**To Reproduce**
1. Go to 'Attendace'
2. Click on 'Create'
3. Fill form + try to safe (not possible)
5. See error + minor error tool-tip overlaps form

**Expected behavior**
The modal has too many options. Only start and end-date and times should be available. "At work" hours should be calculated automatically based on these. Minimum hours and overrtime are not needed here. 
It should be possible to create the attendance entry on own behalf (see https://github.com/horilla-opensource/horilla/issues/21) and on behalf of someone else (if subordinates are assigned).

**Screenshots**
<img width="1464" alt="Bildschirmfoto 2023-08-02 um 21 22 59" src="https://github.com/horilla-opensource/horilla/assets/10340538/0523ddf4-327a-4458-876e-a18f8d32bd04">

**Comment by horilla-opensource** [comment]
Hi @borishinzer,
We get your concern on the attendance addition for the user level and we are working on it.
We'll soon update it to the main code.
Also we'll try to make the modal form much more simpler.
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have fixed the issue with the form save and added the feature for the user to request their missing attendance.
[https://github.com/horilla-opensource/horilla/commit/cf1d29ec07c2fdd36b67f0f29b0bdf4efaf69fbf]
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Not solved for our people. The employee should be able to "ask for correction", maybe give an comment, why he wants the correct (mandatory), example "I missed to punch, but left the company at 17:00". The HR manager should be able to verify and approve it (1 click on approve or decline)

**Comment by horilla-opensource** [comment]
Hi @borishinzer , 
Please refer the below blog :[How Attendance Regularization Using Horilla HRMS in 2023]( https://www.horilla.com/blogs/how-attendance-regularization-using-horilla-hrms/#gsc.tab=0)

**Comment by borishinzer** [comment]
Thanks for the blog post, which is useful. Which rights / settings can we set, so that a user can only see his/her "attendance requests"?

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Currently the admins and reporting managers can see their request along with the requests of their subordinates.
All the other users can see only see his/her requests only.

**Comment by horilla-opensource** [comment]
@borishinzer Is the updates working fine?

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have updated the workflow on this case in the latest commits.
Please check.
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Just checked the workflow, which is now way better. But there are still two issues:
* Punch times (in-out) should calculate the worked times hours automatically, otherwise you could have completely wrong total hours per day and need to do the math on your own
* There should be a possibility to decline the correction with a comment. Eg. if the correction is wrong and/or the description is missing. I don't know if "Cancel" is completely killing the request.

**Comment by borishinzer** [comment]
Also, is there a way that the supervisor ask/ping the employee for correction?

**Comment by borishinzer** [comment]
Can you please explain how the request for correction is done?

**Comment by horilla-opensource** [comment]
**Horilla User Level Current System:**

1. Superuser: With all the permissions
2. Managers (Reporting, Recruitment, Stage, etc...): They can perform limited actions on related subordinates' records.
3. Users with permission: They can perform assigned actions without any restriction on the records.

**Horilla User Level On Upcoming Updates:**

1. Company vise permissions
2. Additional Managers System/ Supervisor system (Supervisors can perform limited actions on the assigned employees)

**When comes to Attendance Request Section:**

1. Superusers can see all records and perform all kinds of actions
2. Users with permission can perform assigned actions.
3. Reporting managers can create, view requests approve, and validate their and subordinates' records
4. Normal Users can request changes to their attendance.

**Comment by horilla-opensource** [comment]
With the Current System: We Recommend you to use create option for the previous attendance date if marked no attendance for the day, If already attendance present on the date then kindly use the request attendance change option. If a user needs to request certain changes to present day's attendance then they needs to request after the shift ends or the next day because the end time is mandatory for the current system.

**Comment by borishinzer** [comment]
I still struggle to send request for check and corrections to employees. Example: An employee forgets to punch out. I see this and therefore can't validate it. Is there a way I can request a review from the employee? Atm. I need to reach out offline to the employee which makes it a lengthy process.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have added new tiles to the main dashboard where the admin gets a view of employees who are not yet logged in/out.
Admins can directly send email from the view itself as a reminder to log in/out .

![Screenshot (10)](https://github.com/horilla-opensource/horilla/assets/131998600/167dd0f0-e02c-4227-868c-a0c4101db2a9)

Please let us know if you have any more concerns.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Thank you very much. That's really great. Only a minor issue: former employees (inactive) shouldn't be shown anywhere, but still are.

**Comment by horilla-opensource** [comment]
#71

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Can we close this issue now as its fixed in #71 ?

**Comment by borishinzer** [comment]
Thank you.

**Comment by horilla-opensource** [comment]
We have also added a new module - _Helpdesk_ into Horilla.
Please do check it out.
After pulling the latest code, please do install the requirements file again as there are some more dependencies needed for the helpdesk module.

With Regards,
**Team Horilla**
