### ISSUE TITLE
can't browse horilla after fresh installation with default databse

### ISSUE THREAD

**Issue by sharukhkhan234** [horilla-opensource/horilla#260]
Hi!
I just wanted to let you know about the issue I was installing Horilla with the default database and fresh installation, after completion of the installation, the server is running correctly, but it can't run in the browser on localhost with the specified port. is there any specific issue regarding the database from your side? plz check it as soon as possible

Regards,

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
We have checked with a fresh pull and fresh database. The system is working fine. The issue is with the default database provided. We'll be updating it asap.
Thanks for pointing it out.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
The test database has been fixed and updated in the master.

With Regards,
**Team Horilla**

**Comment by sharukhkhan234** [comment]
still facing the same issue.
![new_err](https://github.com/user-attachments/assets/24214557-38bc-4e48-ad73-3adbf45b7615)

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
As its a fresh installation, please remove all the migrations files from your apps and remove the test database. Once that's done, do the `git reset --hard` followed by pulling the latest code.

**Comment by sharukhkhan234** [comment]
Ok, I will check it, but plz confirm one thing, that biometric device "zktecho". it can't get the scheduled data, only the active data,
please understand the funda behind that

**Comment by horilla-opensource** [comment]
What did you mean by the scheduled data?

**Comment by sharukhkhan234** [comment]
![attendance](https://github.com/user-attachments/assets/ac3904bc-6822-4adc-908c-2442f3554d73)
![schedule1](https://github.com/user-attachments/assets/16116777-bd32-4114-b1ea-6e44d0538b04)
![schedule2](https://github.com/user-attachments/assets/559c083a-3c48-4077-91e0-610cdb3fe3e6)

check these above pictures, we can get active data from Zkteco device, and in the pic, you can see some data that is got from active live data from Zkteco, but when try to get (scheduled data) from that device, we can't get it. 
the area of using scheduled data, means in case sometimes our server is off, and an employee punches their fingerprint for check-in or check-out while our server is off, in that case we need to get scheduled data but here we are unable to get it.

**Comment by sharukhkhan234** [comment]
I was looking at the code, I think there's no function for getting scheduled data and showing it in the (attendance activities). only I think that defined a function for active data for Zktecho device

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
The team is working on the method to synchronize data from the biometric when the Horilla is down.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,

Can you please check with the latest version of Horilla for the fix?

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
