### ISSUE TITLE
Error when Exporting things related to attendances record

### ISSUE THREAD

**Issue by MrcellSbst** [horilla-opensource/horilla#285]
i got error when exporting work record
![image](https://github.com/user-attachments/assets/18c63fb3-f85f-4c64-b774-ab4aeab4588a)

server running on ubuntu and using postgresql as database

**Comment by MrcellSbst** [comment]
![image](https://github.com/user-attachments/assets/f1842246-952f-406b-9880-7c36517127ce)
also an error when exporting attendance-activity-info-export

**Comment by horilla-opensource** [comment]
Hi @MrcellSbst ,
The issue has been fixed in the commit [[FIX] ATTENDANCE: Fixed work record filtered data import](https://github.com/horilla-opensource/horilla/commit/26e786e18ff3e2c3cb636d88db035abfe8c7349a)

Please pull the latest code and let us know if you face any issues.

With Regards,
**Team Horilla**

**Comment by MrcellSbst** [comment]
![image](https://github.com/user-attachments/assets/633ebec3-e089-4cb4-91c4-a4ea95299195)
the problem still exist

**Comment by MrcellSbst** [comment]
I already pull the newest code
try to export again and still having value error

**Comment by horilla-opensource** [comment]
Hi @MrcellSbst ,
From the log, we understand that you are not using the latest code. We have updated the code at line 2083 in `attendance/views/views.py` to fix this error. 
But in the error log you have pasted, its the previous code that we can see.
Please find the below screenshot for the same.

<img width="775" alt="Screenshot 2024-08-19 at 3 49 29 PM" src="https://github.com/user-attachments/assets/1660f630-5b78-4ea8-94c2-72c28fd8bf95">

Please find the fix in the latest code.

With Regards,
**Team Horilla**

**Comment by MrcellSbst** [comment]
sorry, already pull the newest code.

the work record is fixed but attendance activity still having error

log from server:

Internal Server Error: /attendance/attendance-activity-info-export
Traceback (most recent call last):
  File "/root/horilla/horilla/decorators.py", line 234, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/root/horilla/base/methods.py", line 498, in export_data
    company_name = Company.objects.filter(id=employee_company.id)
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/horilla/horilla/decorators.py", line 234, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/root/horilla/horilla/decorators.py", line 41, in _function
    return function(request, *args, **kwargs)
  File "/root/horilla/attendance/views/views.py", line 975, in attendance_activity_export
    return export_data(
  File "/root/horilla/horilla/decorators.py", line 249, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/horilla/base/methods.py", line 498, in export_data
    company_name = Company.objects.filter(id=employee_company.id)
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/horilla/horilla/decorators.py", line 234, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/root/horilla/base/methods.py", line 498, in export_data
    company_name = Company.objects.filter(id=employee_company.id)
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/horilla/horilla/decorators.py", line 249, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/horilla/horilla/decorators.py", line 41, in _function
    return function(request, *args, **kwargs)
  File "/root/horilla/attendance/views/views.py", line 975, in attendance_activity_export
    return export_data(
  File "/root/horilla/horilla/decorators.py", line 249, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/horilla/base/methods.py", line 498, in export_data
    company_name = Company.objects.filter(id=employee_company.id)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by MrcellSbst** [comment]
![image](https://github.com/user-attachments/assets/ed2342c8-4d09-4732-8269-21fda048f719)
another error when exporting attendance info

**Comment by horilla-opensource** [comment]
Hi @MrcellSbst ,
The issue in the attendance export has been fixed and updated in the latest commit.
Please check and let us know if you face any issues.

With Regards,
**Team Horilla**

**Comment by MrcellSbst** [comment]
everything seems working now, thanks
