### ISSUE TITLE
Overtime not updated when the attendance gets edited

### ISSUE THREAD

**Issue by harunmujic** [horilla-opensource/horilla#56]
# Bug Report

## Description

When an attendance gets edited, it looks like the overtime value does not update with it.

## Steps to Reproduce

1. Minimum hours should be set to 8 hours by the administrator
2. Check in
3. Check out after 12 hours
4. Edit the attendance and modify the "Check-out" and "At-work" values so the total hours tracked for that day result in 7,5 hours
5. Inform the Administrator to approve it

## Expected Behavior

After it gets approved the values of "Check-out", "At-work" and "Overtime" should be updated correctly.

## Actual Behavior

After it gets approved the values of "Check-out" and "At-work" are correct, but the "Overtime" value is not updated (displays 4h, although it should display 0)

## Screenshots

<img width="1123" alt="Screenshot 2023-11-13 at 10 41 27" src="https://github.com/horilla-opensource/horilla/assets/99493157/2088a486-08e5-4c64-8e32-bb6526220dd1">

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
We appreciate the time and effort you invested in testing our system and bringing to our attention the issue you encountered.

The issue you have mentioned is solved and updated in out commit [ [FIX] ATTENDANCE: Overtime calculation issue after attendance approval ](https://github.com/horilla-opensource/horilla/commit/61a488b8a512b58104c184ee353698dcc404f727)

Kindly take a moment to check the latest code and confirm if the solution now functions as expected on your end.

Thank you for your collaboration and valuable feedback. If you have any further inquiries or encounter additional issues, please do not hesitate to reach out. We are committed to ensuring the optimal performance of our system.

With Regards,
**Team Horilla**

**Comment by harunmujic** [comment]
It did not fix the old attendance where I noticed the issue. But I guess you added a fix which will fix the new attendances, not the already existing ones. 
Unfortunately, as I have no admin rights in my organisation, I can't really test it out. We can consider it as fixed and if it happens again in the future, I will make sure to open a new issue so you can check it.

**Comment by horilla-opensource** [comment]
Sure.
Do let us know if you have any more concerns.

With Regards,
**Team Horilla**
