### ISSUE TITLE
Update_compensation on net_pay is giving error on generating payslip

### ISSUE THREAD

**Issue by unreal0901** [horilla-opensource/horilla#576]
Can you check and verify as
when i create a update compensation on net pay for a specific employee.
It is throwing the following error when generating payslips:

```bash
Internal Server Error: /payroll/create-payslip
Traceback (most recent call last):
  File "/home/ec2-user/project/horilla/horilla/decorators.py", line 234, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/home/ec2-user/project/horilla/horilla/decorators.py", line 41, in _function
    return function(request, *args, **kwargs)
  File "/home/ec2-user/project/horilla/payroll/views/component_views.py", line 909, in create_payslip
    calculate_employer_contribution(data)
  File "/home/ec2-user/project/horilla/payroll/methods/methods.py", line 560, in calculate_employer_contribution
    amount * object.employer_rate
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

This is the data am getting in save method of Deduction form creation:

```
json
{
  "csrfmiddlewaretoken": "kiroZ/2LaPFeQWv4tZSw7r1fK0bUIOZ1GgbnG6hzPEfb131C...",
  "title": "net_pay_compensation_Deductions",
  "one_time_date": "2025-03-10",
  "specific_employees": "6",
  "search": "",
  "is_pretax": "on",
  "field": "",
  "condition": "",
  "value": "",
  "update_compensation": "net_pay",
  "amount": "1000",
  "based_on": "",
  "rate": "0.0",
  "employer_rate": "0.0",
  "maximum_amount": "",
  "maximum_unit": "month_working_days",
  "if_choice": "basic_pay",
  "if_condition": "gt",
  "if_amount": "0.0",
  "start_range": "",
  "end_range": ""
}
```

As you can see the based on will be saved as None in the database, but now in calculate employee contribution funciton , its throwing that error.

```python
def calculate_employer_contribution(data):
    """
    This method is used to calculate the employer contribution
    """
    pay_head_data = data["pay_data"]
    deductions_to_process = [
        pay_head_data.get("pretax_deductions"),
        pay_head_data.get("post_tax_deductions"),
        pay_head_data.get("tax_deductions"),
        pay_head_data.get("net_deductions"),
    ]

    for deductions in deductions_to_process:
        if deductions:
            for deduction in deductions:
                if (
                    deduction.get("deduction_id")
                    and deduction.get("employer_contribution_rate", 0) > 0
                ):
                    object = Deduction.objects.filter(
                        id=deduction.get("deduction_id")
                    ).first()
                    if object:
                        amount = pay_head_data.get(object.based_on)
                        employer_contribution_amount = (
                            amount * object.employer_rate
                        ) / 100
                        deduction["based_on"] = object.based_on
                        deduction["employer_contribution_amount"] = (
                            employer_contribution_amount
                        )
    return data
```

Also i think employer_contribution for other type of taxes is not calculating correctly.

**Comment by horilla-opensource** [comment]
Hi @unreal0901 ,  

Thanks for reporting this issue!  

It looks like the `based_on` field is getting saved as `None` in the database, which is causing the `TypeError` in the `calculate_employer_contribution` function when trying to multiply it with `employer_rate`.  

We will check and verify the issue, including the calculation of employer contributions for other tax types. We'll update you once we have a fix.  

Best Regards,  
**Team Horilla**

**Comment by M-Shariq-546** [comment]
@horilla-opensource Please assign this task to me i will do this

**Comment by M-Shariq-546** [comment]
@unreal0901 I am getting this as payload how you get above mentioned and i haven't have this error

`====== request data  <QueryDict: {'csrfmiddlewaretoken': ['E1WaBEniawxbQ9qnECE579kmkoFGMbzCJVCF0c62wibVY1gTNmS0SCn7hT7kdamw'], 'employee_id': ['7'], 'start_date': ['2025-03-01'], 'end_date': ['2025-03-14']}>`

**Comment by unreal0901** [comment]
@M-Shariq-546 
Employer contribution for other taxes such as pre_tax_deductions, post_tax_deductions,  tax_deductions,  net_deductions .
**Steps to Reproduce:**

1. Navigate to the **Deductions** tab in the **Payroll** module.
2. Select **Update Compensation**.
3. Choose **Net Pay** from the dropdown menu.

![Image](https://github.com/user-attachments/assets/587f2c3b-9565-4a6c-9997-e89573d57d0d)

4. In the `save` method of `DeductionForm`, the `based_on` field is being passed as empty.
5. This field is utilized in the `calculate_employer_contribution` function, which can be traced from the `generate_payslip` view .
6. View payroll_calculation method for checking how taxes are being calculated.

To understand how the `employer_contribution` is calculated, refer to the following URL:
```python
path("generate-payslip", component_views.generate_payslip, name="generate-payslip"),
```

7. when deduction is saved, then generate the payslip for the same employee.

**Issue:**
An error is displayed, and the employer contribution is not being calculated correctly for other taxes.

![Image](https://github.com/user-attachments/assets/12c49b7a-715a-4a54-8757-53fdf56efc64)

**Comment by M-Shariq-546** [comment]
> generate-payslip

["Screen Recording 2025-03-14 at 12.36.57 PM.mov"](url)

**Comment by unreal0901** [comment]
@M-Shariq-546 
we have to first create the deduction based on update-compensation > net_pay and then generate payslip.
Then that error is coming .

**Comment by M-Shariq-546** [comment]
> [@M-Shariq-546](https://github.com/M-Shariq-546) we have to first create the deduction based on update-compensation > net_pay and then generate payslip. Then that error is coming .

Provide me your email i will send you screen recording that i did the same

**Comment by unreal0901** [comment]
@M-Shariq-546 
Send me the sqlite file also with the recording.
email: rawatas0901@gmail.com

**Comment by M-Shariq-546** [comment]
@unreal0901 check it now on your email

**Comment by unreal0901** [comment]
yes in your case, its working.
I will try it again after flushing the database.

**Comment by unreal0901** [comment]
I have checked with latest branch and with fresh database.
Still this issue is occurring, am attaching the video link to the issue with error in console.
The amount is coming None as the based_on is not set when saving in DeductionForm
[Video Link](https://streamable.com/x87xis)

Error coming:

![Image](https://github.com/user-attachments/assets/267886e8-5028-4290-8378-ed80647522cc)

**Comment by M-Shariq-546** [comment]
got it you are facing issue due to none saving in amount field i am fixing it and will update it soon

**Comment by M-Shariq-546** [comment]
> [@M-Shariq-546](https://github.com/M-Shariq-546) None is coming in amount because, based_on in DeductionForm save method is empty string. Try to create the Deduction and add a breakpoint at save method of DeductionForm, the based_on is empty string. Because of that at employer_contribution method we are getting amount as None.

Implemented @unreal0901  so @horilla-opensource Please review and merge the code for issue fixing and making horilla working for users [#603 ](https://github.com/horilla-opensource/horilla/pull/603)

**Comment by unreal0901** [comment]
@M-Shariq-546 
error stack trace is pointing at calculate_employer_contribution.

```python
def calculate_employer_contribution(data):
```

Here amount is fetched on the basis of based_on, which is empty string .
so we are getting the amount variable as None
```python
      amount = pay_head_data.get(object.based_on)
                        employer_contribution_amount = (
                            amount * object.employer_rate
                        ) / 100
```

**Comment by M-Shariq-546** [comment]
yes i fixed it once the code merged you will get that

**Comment by unreal0901** [comment]
I tried your changes, issue is still there.
we can do this
```python
self.instance.based_on = 'net_pay'
```
but basic_pay and gross_pay is coming from frontend , why net_pay is not coming? 

```python
    update_compensation = models.CharField(
        null=True,
        blank=True,
        max_length=10,
        choices=[
            (
                "basic_pay",
                _("Basic pay"),
            ),
            ("gross_pay", _("Gross Pay")),
            ("net_pay", _("Net Pay")),
        ],
        help_text=_(
            "Update compensation is used to update \
                   pay-head before any other deduction calculation starts"
        ),
    )
```

from frontend based_on is coming empty, even we have it here.

**Comment by unreal0901** [comment]
yea its create-payslip only.
They do almost the same thing.
can you check in your flow if this method is being called.
```
def calculate_employer_contribution(data):
```

I can send you my sqlite file if you want .

**Comment by M-Shariq-546** [comment]
> calculate_employer_contribution

yes in my flow this function is called and also gives me 200

**Comment by unreal0901** [comment]
I sent the DB, please check .

**Comment by M-Shariq-546** [comment]
> I sent the DB, please check .

ok

**Comment by M-Shariq-546** [comment]
@unreal0901 your db entries are wrong that's why error persists

**Comment by unreal0901** [comment]
but i ran both of these commands before generating the payslip:
```bash
python manage.py makemigrations
python manage.py migrate
```

Also i haven't touched the entries manually.
So how can i fix this issue?

**Comment by M-Shariq-546** [comment]
> but i ran both of these commands before generating the payslip:
> 
> python manage.py makemigrations
> python manage.py migrate
> Also i haven't touched the entries manually. So how can i fix this issue? I just created deductions, then fedtax slabs, contract, activate the contract, and then create-payslip

leave it resolved

**Comment by unreal0901** [comment]
@horilla-opensource am closing this issue for now,  but this issue is still in the application.
